trigger:
- adarsh

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'AdarshDockerHub'
    command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'AdarshDockerHub'
    repository: 'adarshmurali/dockerpython'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'



